# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# AutoDUT CI Tool pipeline. For demo pipelines see 'gitlab' module
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Global pipeline rules (can be narrowed inside each job)
workflow:
  rules:
    #- if: '$CI_COMMIT_BRANCH == "master"'
    #- if: '$CI_COMMIT_TAG'
    - if: '$CI_PIPELINE_SOURCE == "web"'
    #- if: '$CI_PIPELINE_SOURCE == "api"'

# Pipeline stages
stages:
  - build_docker_image

# Jobs

# Build and upload docker image
Build docker image:
  stage: build_docker_image
  script:
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY};
    - docker buildx build tools/docker -t ${CI_REGISTRY_IMAGE}:latest --no-cache --pull --platform linux/386;
    - docker push ${CI_REGISTRY_IMAGE}:latest;
  artifacts: {}
